---
- hosts: benchmark_hosts
  become: True
  vars:
    _pool_name: "{{ fiobench_pool_name | default('fiobench') }}"
    _ceph_args: "--id {{ fiobench_client_name | default('fiobench') }}"
  tasks:
    - name: Check for fiobench.keyring
      stat:
        path: /etc/ceph/ceph.client.fiobench.keyring
      register: keyring
    - name: Delete image
      command: "rbd {{ _ceph_args }} remove {{ _pool_name }}/{{ item }}"
      with_items:
        - "bench_direct_RBD-{{ inventory_hostname_short }}"
      when: keyring.stat.exists
      register: rbd_rm_result
      failed_when: rbd_rm_result.rc not in [0,2]

# Cleanup the benchmark pool if we created it
- hosts: mons
  become: True
  tasks:
    - include_tasks: fio_benchmark_remove_pool.yml
      vars:
        _pool_name: "{{ fiobench_pool_name | default('fiobench') }}"
      when: fio_bench_remove_pool | default(true)
