#!/usr/bin/env bash
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -xeuo pipefail

echo "Gate job started"
echo "+-------------------- START ENV VARS --------------------+"
env
echo "+-------------------- START ENV VARS --------------------+"

export RE_JOB_SCENARIO=${RE_JOB_SCENARIO:-"functional"}
export RPC_OPENSTACK_DIR=${RPC_OPENSTACK_DIR:-/opt/rpc-openstack}
export RPC_MAAS_DIR=${RPC_MAAS_DIR:-/etc/ansible/ceph_roles/rpc-maas}
export TEST_RPC_MAAS=${TEST_RPC_MAAS:-True}
export BOOTSTRAP_OPTS=${BOOTSTRAP_OPTS:-""}
export DATA_DISK_MIN_SIZE_GB=${DATA_DISK_MIN_SIZE_GB:-50}
export ANSIBLE_ADDITIONAL_VARS=${ANSIBLE_ADDITIONAL_VARS:-""}

# Install python2 for Ubuntu 16.04 and CentOS 7
if which apt-get; then
    sudo apt-get update && sudo apt-get install -y python
fi

if which yum; then
    sudo yum install -y python
fi

# Install pip.
if ! which pip; then
  curl --silent --show-error --retry 5 \
    https://bootstrap.pypa.io/get-pip.py | sudo python2.7
fi

# Install bindep and tox with pip.
sudo pip install bindep tox

# CentOS 7 requires two additional packages:
#   redhat-lsb-core - for bindep profile support
#   epel-release    - required to install python-ndg_httpsclient/python2-pyasn1
if which yum; then
    sudo yum -y install redhat-lsb-core epel-release
fi

function _set_rpco_vars {
  ## Copy over the keystone_auth_admin_password from OSA --> Ceph
  if ! grep -q keystone_auth_admin_password ${CLONE_DIR}/tests/test-vars-openstack.yml; then
    grep keystone_auth_admin_password /etc/openstack_deploy/user_osa_secrets.yml >> ${CLONE_DIR}/tests/test-vars-openstack.yml
  fi
  ## Add the rsyslog_container into the inventory
  if ! grep -q rsyslog_container ${CLONE_DIR}/tests/inventory_rpco; then
    RSYSLOG_HOST=$(lxc-ls -f | grep rsyslog_container | awk {'print $1'})
    RSYSLOG_HOST_IP=$(grep $RSYSLOG_HOST /etc/hosts | awk {' print $1 '})
    echo -e "\n[rsyslog_all]\n$RSYSLOG_HOST ansible_host=$RSYSLOG_HOST_IP" >> ${CLONE_DIR}/tests/inventory_rpco
  fi
  # Generate Cinder Ceph Client UUID
  CINDER_CEPH_CLIENT_UUID=$(uuidgen)
  echo "cinder_ceph_client_uuid: $CINDER_CEPH_CLIENT_UUID" >> /etc/openstack_deploy/user_rpc_ceph_vars.yml
}

function _configure_rpco {
  if [[ ! -d /opt/rpc-openstack ]]; then
    git clone https://github.com/rcbops/rpc-openstack -b newton-rc --recursive ${RPC_OPENSTACK_DIR}
  fi
  pushd ${RPC_OPENSTACK_DIR}
    ## Dont use the specified Ceph inventory
    unset ANSIBLE_INVENTORY
    ## Set the RPC_ARTIFACT_MODE vars
    export RPC_APT_ARTIFACT_ENABLED=no
    export RPC_APT_ARTIFACT_MODE=loose
    ## Use the openstack-ansible binary
    export ANSIBLE_BINARY="openstack-ansible"
    ## Bootstrap RPC-O's ansible
    bash scripts/bootstrap-ansible.sh
    cp ${CLONE_DIR}/tests/rpco_vars/user_rpc_ceph_vars.yml /etc/openstack_deploy/user_rpc_ceph_vars.yml
    bash scripts/bootstrap-aio.sh
    ## Build out the hosts, infrastructure and keystone only.
    pushd ${RPC_OPENSTACK_DIR}/openstack-ansible/playbooks
      cp ${CLONE_DIR}/tests/rpco_vars/cinder.yml.ceph /etc/openstack_deploy/conf.d/cinder.yml
      cp inventory/env.d/cinder.yml /etc/openstack_deploy/env.d/cinder.yml
      sed -i 's/is_metal: true/is_metal: false/g' /etc/openstack_deploy/env.d/cinder.yml
      sed -i "s/aio1/$(hostname)/" /etc/openstack_deploy/openstack_user_config.yml
      sed -i "s/aio1/$(hostname)/" /etc/openstack_deploy/conf.d/*.yml
      ${ANSIBLE_BINARY} setup-hosts.yml
      ${ANSIBLE_BINARY} setup-infrastructure.yml
      ${ANSIBLE_BINARY} os-keystone-install.yml
    popd
  popd
  ## Set the binary and inventory back to ceph's version.
  export ANSIBLE_BINARY="ceph-ansible-playbook"
  export ANSIBLE_INVENTORY="${CLONE_DIR}/tests/inventory_rpco"
  export ANSIBLE_ADDITIONAL_VARS="-e @tests/test-vars-openstack.yml"
}

function _deploy_rpco {
  unset ANSIBLE_INVENTORY
  export ANSIBLE_BINARY="openstack-ansible"
  pushd ${RPC_OPENSTACK_DIR}/openstack-ansible/playbooks
    ${ANSIBLE_BINARY} os-glance-install.yml
    ${ANSIBLE_BINARY} os-cinder-install.yml
    ${ANSIBLE_BINARY} os-nova-install.yml
    ${ANSIBLE_BINARY} os-neutron-install.yml
    ${ANSIBLE_BINARY} os-tempest-install.yml
  popd
}

function _get_data_disk {
  # Get minimum disk size
  DATA_DISK_MIN_SIZE="$((1024**3 * ${DATA_DISK_MIN_SIZE_GB} ))"

  # Determine the largest secondary disk device that meets the minimum size
  DATA_DISK_DEVICE=$(lsblk -brndo NAME,TYPE,RO,SIZE | awk '/d[b-z]+ disk 0/{ if ($4>m && $4>='$DATA_DISK_MIN_SIZE'){m=$4; d=$1}}; END{print d}')

  # Only set the secondary disk device option if there is one
  if [ -n "${DATA_DISK_DEVICE}" ]; then
    export BOOTSTRAP_OPTS="-e bootstrap_host_data_disk_device=${DATA_DISK_DEVICE}"
  fi
}

export CLONE_DIR="$(pwd)"
export ANSIBLE_INVENTORY="${CLONE_DIR}/tests/inventory"
export ANSIBLE_PARAMETERS="-e @${CLONE_DIR}/tests/test-vars.yml -e @${RPC_MAAS_DIR}/tests/user_rpcm_secrets.yml"
export ANSIBLE_BINARY="${ANSIBLE_BINARY:-ceph-ansible-playbook}"
bash scripts/bootstrap-ansible.sh
# Clone the test repos when not integrating with RPC-O
# RPC-O has existing lxc roles that will conflict
if [ "${RE_JOB_SCENARIO}" != "rpco_newton" ]; then
  ${ANSIBLE_BINARY} playbooks/git-clone-repos.yml \
                   -i ${ANSIBLE_INVENTORY} \
                   -e role_file=../tests/ansible-role-test-requirements.yml
fi
## Clone RPC-O directory into /opt
if [ "${RE_JOB_SCENARIO}" == "rpco_newton" ]; then
  _configure_rpco
  _set_rpco_vars
fi
## Set the inventory and include the additional overrides vars file
if [ "${RE_JOB_SCENARIO}" = "keystone_rgw" ]; then
  export ANSIBLE_INVENTORY="${CLONE_DIR}/tests/inventory_rgw"
  export ANSIBLE_ADDITIONAL_VARS="-e @tests/test-vars-rgw.yml"
fi
if [ "${RE_JOB_SCENARIO}" = "bluestore" ]; then
  export ANSIBLE_ADDITIONAL_VARS="-e @tests/test-vars-bluestore.yml"
fi
if [[ ! -d tests/common ]]; then
  git clone https://github.com/openstack/openstack-ansible-tests -b stable/pike tests/common
fi
_get_data_disk
${ANSIBLE_BINARY} tests/setup-ceph-aio.yml \
                 -i ${ANSIBLE_INVENTORY} \
                 -e @tests/test-vars.yml \
                 ${ANSIBLE_ADDITIONAL_VARS} ${BOOTSTRAP_OPTS}
if [ "${RE_JOB_SCENARIO}" == "rpco_newton" ]; then
  _deploy_rpco
fi
# Use the rpc-maas deploy to test MaaS
if [ "${TEST_RPC_MAAS}" != "False" ] && [ "${RE_JOB_SCENARIO}" == "functional" ]; then
  pushd ${RPC_MAAS_DIR}
    export RE_JOB_SCENARIO="ceph"
    bash tests/test-ansible-functional.sh
  popd
fi
