---
- hosts: benchmark_hosts
  become: true
  tasks:
    - include_tasks: fio_benchmark_run_tasks.yml
      vars:
        fio_job_name: "{{ _bench_list.name }}"
        run_id: "{{ ansible_date_time.iso8601_basic_short }}"
      with_items: "{{ fio_bench_list }}"
      when: _bench_list.run_bench
      loop_control:
        loop_var: _bench_list
