---
- hosts: benchmark_hosts
  become: True
  gather_facts: True
  tasks:
    - name: Run hummingbird bench and record version/config info
      shell: >
        echo "Humminbird Version: `/opt/ceph_bench/hummingbird version`\n
              Bench Config Used:\n`cat /opt/ceph_bench/rgw_bench_test.conf`\n\n
              Hummingbird Benchmark Output:\n`/opt/ceph_bench/hummingbird bench /opt/ceph_bench/rgw_bench_test.conf`" \
                | tee /opt/ceph_bench/logs/rgw_bench_test.conf.{{ ansible_date_time.iso8601_basic_short }}.log
      register: hummingbird_bench_output
      when: rgw_bench|default(true)
    - name: Debug hummingbird-bench outputs
      debug:
        var: hummingbird_bench_output.stdout_lines
    - name: fetch log file
      fetch:
        src: "/opt/ceph_bench/logs/rgw_bench_test.conf.{{ ansible_date_time.iso8601_basic_short }}.log"
        dest: "/opt/ceph_bench/logs/{{ ansible_date_time.iso8601_basic_short }}/{{ inventory_hostname_short }}/rgw_bench_test.conf.log"
        flat: true
