sudo: required

language: c

services:
  - docker

script:
  - cd docs && make docs
  - sudo touch _build/html/.nojekyll # Is there a better way to do this?

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: docs/_build/html
  on:
    branch: master